[package]
name = "rspack-rust-api"
version = "0.1.0"
edition = "2021"

[dependencies]
rspack_ids= { git = "https://github.com/web-infra-dev/rspack", branch = "main"}
rspack_binding_options= { git = "https://github.com/web-infra-dev/rspack", branch = "main"}
rspack_hook= { git = "https://github.com/web-infra-dev/rspack", branch = "main", package = "rspack_hook"}
rspack_plugin_javascript= { git = "https://github.com/web-infra-dev/rspack", branch = "main", package = "rspack_plugin_javascript"}
rspack_error = { git = "https://github.com/web-infra-dev/rspack", branch = "main", package = "rspack_error"}
rspack_core = { git = "https://github.com/web-infra-dev/rspack", branch = "main"}
rspack_plugin_entry = { git = "https://github.com/web-infra-dev/rspack", branch = "main", package = "rspack_plugin_entry" }
rspack_fs = { git = "https://github.com/web-infra-dev/rspack", branch = "main", package = "rspack_fs" }
serde_json = "1.0.113"
base64 = "0.22.1"
tokio = {features = ["full"], version = "1.38.0"}
miette = { version = "*" }
hyper = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bytes = "1.6.0"
pretty_env_logger = "0.5.0"
wasm-bindgen = "0.2.92"
